### ISSUE TITLE
FYI: end–of–life for components

### ISSUE THREAD

**Issue by cdn** [MyLab-odyssey/EDm_BLE#2]
[Mouser listing](https://www.mouser.co.uk/ProductDetail/RF-Digital-Wireless/RFD22301) for RFduino states its EOL this year (2018).

**Comment by cdn** [comment]
Same applies to the resonator: CSTCE16M0V53-R0

**Comment by MyLab-odyssey** [comment]
Thanks for the info! Nothing is designed to last ;-) The resonator production started in 2000, but Murata lists a recommended alternative: [CSTNE16M0V530000R0](https://www.murata.com/products/productdetail?partno=CSTNE16M0V530000R0) same specs but with better temperature range.

Also the RFduino is quite old and HEPTAGON released the Simblee about three years ago. It is very compatible regarding basic RFduino features and there is a OSHpark project for an [adapter board](https://oshpark.com/shared_projects/TrsQzmnW).

I updated the BOM for those components.

**Comment by cdn** [comment]
Can you confirm the Microchip MCP1755 LDO Voltage Regulator is the 5V version? The chip(s) it supplies appear to require 3.3V.

**Comment by MyLab-odyssey** [comment]
Uuups. This is a nasty typo! THX for the comment as VCCIO is indeed 3.3V and you have to use the appropriate variant: [MCP1755T-3302E/OT](https://www2.mouser.com/ProductDetail/Microchip-Technology/MCP1755T-3302E-OT?qs=sGAEpiMZZMsGz1a6aV8DcHoYFh2%2fqM5DZR1GkFHnTSo=)

(BOM edited)
